#!/usr/bin/env python3
"""
Genera gif_exercise_catalog.dart da tutti i file in all_gifs/.
Copia anche tutti i GIF in entrambe le app.

USO:
  python generate_gif_catalog.py
"""

import os
import re
import shutil
from pathlib import Path

BASE       = Path(__file__).parent
ALL_GIFS   = BASE / "all_gifs"
APP_CLIENT = BASE / "app_cliente" / "assets" / "gif"
APP_PT     = BASE / "app_pt"     / "assets" / "gif"
OUT_CLIENT = BASE / "app_cliente" / "lib" / "gif_exercise_catalog.dart"
OUT_PT     = BASE / "app_pt"     / "lib" / "gif_exercise_catalog.dart"

# ── Categorizzazione automatica da keywords nel nome slug ─────────────────────
def categorize(slug: str) -> str:
    s = slug.lower()

    # Cardio
    cardio_kw = ['jump-rope', 'burpee', 'running', 'assault-air', 'stationary-bike',
                 'high-knee', 'shadow-boxing', 'punches', 'mountain-climber',
                 'jump-squat', 'box-jump', 'speed-skater', 'ski-step', 'jump-lunge',
                 'power-skip', 'high-knees', 'sprint', 'wheel-run', 'skipping']
    if any(k in s for k in cardio_kw):
        return 'cardio'

    # Core / addominali
    core_kw = ['plank', 'crunch', 'sit-up', 'leg-raise', 'flutter-kick', 'oblique',
               'ab-roller', 'hanging-leg', 'wipers', 'v-up', 'dragon-flag',
               'dead-bug', 'hollow-body', 'russian-twist', 'toe-touch', 'windmill',
               'side-bend', 'elbow-to-knee', 'bicycle', 'mountain', 'vacuum']
    if any(k in s for k in core_kw):
        return 'core'

    # Glutei
    glute_kw = ['hip-thrust', 'glute-bridge', 'donkey-kick', 'fire-hydrant',
                'adductor', 'abductor', 'cossack', 'frog-pump', 'banded-donkey',
                'kneeling-hip', 'resistance-band-hip', 'side-hip', 'standing-hip']
    if any(k in s for k in glute_kw):
        return 'glutei'
    if 'glute' in s and 'bridge' not in s:
        return 'glutei'

    # Gambe
    leg_kw = ['squat', 'lunge', 'leg-press', 'leg-curl', 'leg-extension',
              'step-up', 'calf-raise', 'hamstring', 'quad', 'nordic',
              'goblet', 'front-squat', 'back-squat', 'sumo', 'hack-squat',
              'split-squat', 'pistol', 'box-squat', 'pin-squat', 'leg-day',
              'seated-calf', 'standing-calf', 'wall-sit']
    if any(k in s for k in leg_kw):
        return 'gambe'

    # Petto
    chest_kw = ['bench-press', 'chest-press', 'push-up', 'fly', 'crossover',
                'chest-fly', 'cable-fly', 'pec', 'inner-chest', 'decline-press',
                'incline-press', 'hex-press', 'low-cable', 'high-cable']
    if any(k in s for k in chest_kw):
        return 'petto'
    # push-up generici
    if 'push' in s and ('up' in s or 'press' in s) and 'shoulder' not in s and 'overhead' not in s:
        return 'petto'

    # Dorso
    back_kw = ['pull-up', 'chin-up', 'lat-pulldown', 'pulldown', 'bent-over-row',
               'seated-row', 't-bar-row', 'cable-row', 'dumbbell-row', 'barbell-row',
               'meadows-row', 'kroc-row', 'band-row', 'inverted-row', 'australian',
               'renegade-row', 'rack-pull', 'deadlift', 'stiff-leg', 'romanian',
               'pullover', 'lat-pull', 'wide-grip-row', 'single-arm-row']
    if any(k in s for k in back_kw):
        return 'dorso'
    if 'row' in s and 'overhead' not in s:
        return 'dorso'

    # Braccia
    arm_kw = ['curl', 'tricep', 'bicep', 'skull-crusher', 'kickback', 'preacher',
              'hammer-curl', 'zottman', 'concentration-curl', 'cable-curl',
              'overhead-tricep', 'rope-pushdown', 'pushdown', 'dips', 'closegrip',
              'close-grip', 'reverse-curl', 'wrist-curl', 'forearm']
    if any(k in s for k in arm_kw):
        return 'braccia'

    # Spalle
    shoulder_kw = ['shoulder', 'lateral-raise', 'front-raise', 'military-press',
                   'overhead-press', 'shrug', 'upright-row', 'face-pull', 'rear-delt',
                   'arnold', 'landmine-press', 'push-press', 'thruster',
                   'band-press', 'dumbbell-press', 'barbell-press', 'kettlebell-press',
                   'cable-press', 'behind-neck', 'one-arm-press']
    if any(k in s for k in shoulder_kw):
        return 'spalle'

    return 'altro'


def slug_to_name(filename: str) -> str:
    """barbell-curl.gif → Barbell Curl"""
    slug = filename.replace('.gif', '')
    # Split on hyphens, title-case each word
    words = slug.replace('-', ' ').split()
    # Keep common acronyms uppercase
    acronyms = {'ez', 'trx', 'rdl', 'sumo'}
    return ' '.join(w.upper() if w.lower() in acronyms else w.title() for w in words)


def dart_escape(s: str) -> str:
    return s.replace("'", "\\'")


def generate_dart(gifs: list[str]) -> str:
    lines = [
        "// Auto-generated by generate_gif_catalog.py — do not edit manually",
        "// ignore_for_file: lines_longer_than_80_chars",
        "",
        "import 'exercise_catalog.dart';",
        "",
        "/// Catalogo esercizi completo dal database GIF (${count} esercizi)".replace("${count}", str(len(gifs))),
        "/// Usa findAnyExercise() invece di findExercise() per cercare in entrambi i cataloghi.",
        "const List<ExerciseInfo> kGifCatalog = [",
    ]

    for gif in gifs:
        slug = gif.replace('.gif', '')
        name = slug_to_name(gif)
        cat = categorize(slug)
        lines.append(f"  ExerciseInfo(name: '{dart_escape(name)}', nameEn: '{dart_escape(name)}', category: '{cat}', muscleImages: [], primaryMuscle: '', secondaryMuscles: '', execution: '', tips: '', gifFilename: '{slug}'),")

    lines += [
        "];",
        "",
        "/// Cerca in kGifCatalog per nome esatto o parziale.",
        "ExerciseInfo? findInGifCatalog(String query) {",
        "  final q = query.trim().toLowerCase();",
        "  // Exact match",
        "  for (final e in kGifCatalog) {",
        "    if (e.name.toLowerCase() == q) return e;",
        "  }",
        "  // Partial match (ogni parola del query presente nel nome)",
        "  final words = q.split(' ').where((w) => w.length > 2).toList();",
        "  if (words.isNotEmpty) {",
        "    for (final e in kGifCatalog) {",
        "      final en = e.name.toLowerCase();",
        "      if (words.every((w) => en.contains(w))) return e;",
        "    }",
        "  }",
        "  return null;",
        "}",
        "",
        "/// Cerca in kExerciseCatalog prima, poi in kGifCatalog.",
        "ExerciseInfo? findAnyExercise(String name) {",
        "  return findExercise(name) ?? findInGifCatalog(name);",
        "}",
        "",
        "/// Lista di tutti i GIF disponibili (slug senza .gif), ordinati alfabeticamente.",
        "/// Usata dal GIF picker nel PT app.",
        "List<String> get allGifSlugs =>",
        "    kGifCatalog.map((e) => e.gifFilename!).toList();",
    ]

    return '\n'.join(lines) + '\n'


# ── MAIN ──────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    gifs = sorted(f for f in os.listdir(ALL_GIFS) if f.endswith('.gif'))
    print(f"Trovate {len(gifs)} GIF in {ALL_GIFS}")

    dart_code = generate_dart(gifs)

    for out in [OUT_CLIENT, OUT_PT]:
        out.write_text(dart_code, encoding='utf-8')
        print(f"Scritto: {out}")

    print()
    print("Copio GIF nelle app...")
    copied = 0
    skipped = 0
    for gif in gifs:
        src = ALL_GIFS / gif
        for dst_dir in [APP_CLIENT, APP_PT]:
            dst = dst_dir / gif
            if not dst.exists():
                shutil.copy2(src, dst)
                copied += 1
            else:
                skipped += 1

    print(f"Copiate: {copied}, già presenti: {skipped}")
    print(f"Totale GIF nelle app: {len(list(APP_CLIENT.glob('*.gif')))}")
    print()
    print("Fatto! Ora aggiorna il codice Dart e ricompila le app.")
